name: MoodRingLog
options:
  bundleIdPrefix: com.shimondeitel.moodringlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  MoodRingLog:
    type: application
    platform: iOS
    sources:
      - path: MoodRingLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.moodringlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: MoodRingLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  MoodRingLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MoodRingLogTests
      - path: MoodRingLog.storekit
    dependencies:
      - target: MoodRingLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.moodringlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  MoodRingLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MoodRingLogUITests
    dependencies:
      - target: MoodRingLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.moodringlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  MoodRingLog:
    build:
      targets:
        MoodRingLog: all
        MoodRingLogTests: [test]
        MoodRingLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: MoodRingLog.storekit
    test:
      config: Debug
      storeKitConfiguration: MoodRingLog.storekit
      targets:
        - MoodRingLogTests
        - MoodRingLogUITests
    archive:
      config: Release
